description: My model port 8085
prompts:
- '{{question}}'
providers:
- id: http
  config:
    request: |-
      POST /cosmetics-answer HTTP/1.1
      Host: 127.0.0.1:8085
      Content-Type: application/json
      Accept: application/json
      
      {"question": "{{question}}"}                       "
    transformResponse: json.answer
tests:
- vars:
    question: What is the best vitamin/supplement for ageing skin?
  assert:
  - type: llm-rubric
    value: '"Signs of ageing start to show on the skin from around the mid-20s onwards"
      explains Beth. "This can display as fine lines, sagging and dryness. Collagen
      peptide supplements have been suggested to replenish the collagen we lose through
      the ageing process, helping to plump out fine lines, improve elasticity, tighten
      skin, and even support healthy joints and strong bones. This area of research
      is largely novel but highly promising, with many studies supporting the claim".'
- vars:
    question: What is the best vitamin/supplement for dull skin?
  assert:
  - type: llm-rubric
    value: For achieving that luminous look we all long for, Beth advises taking a
      vitamin C supplement. "Vitamin C is another skin care hero, with further benefits
      such as boosting collagen formation, supporting the immune system and reducing
      fatigue. Vitamin C fires up fibroblast cells within the skin which are involved
      in the production of collagen – the structural protein in our bodies that keeps
      skin smooth and youthful. Furthermore, vitamin C is an antioxidant. This means
      it can reduce the oxidative stress and free radical damage that may be associated
      with dull skin, leaving your skin brighter and smoother".
- vars:
    question: What is the best vitamin supplement for oily and blemish-prone skin?
  assert:
  - type: llm-rubric
    value: '"The B vitamins are fantastic all-rounders when it comes to skin health"
      says Beth. "Vitamin B12 in particular is a vitamin found in animal-based foods
      that has a wide variety of benefits and uses, including supporting the nervous
      system, mental and cognitive health, a healthy immune system and boosting hair,
      skin and nail health. Deficiencies in this vital vitamin can lead to acne-prone
      skin and hyperpigmentation, so supplementation can help reduce risk of deficiency
      and improve skin texture and tone, especially in vegetarians and vegans".'
- vars:
    question: Are there any vitamin combinations that shouldn't be taken together?
  assert:
  - type: llm-rubric
    value: '"While some vitamin and mineral combinations work well together (eg. Vitamin
      C paired with iron to boost iron absorption), others can negatively affect absorption
      and hinder how our bodies utilise nutrients" warns Beth. "For example, vitamin
      C has been suggested to keep your body from using vitamin B12 so well. Likewise,
      mineral supplements (calcium, zinc and magnesium) should not be taken at the
      same time, as these nutrients may compete for absorption". Always make sure
      to follow professional advice when it comes to starting a new vitamin or supplement.'
sharing:
  appBaseUrl: https://promptfoo.imutably.com
